apiVersion: v1
kind: Service
metadata:
  name: kubernetes-2-desafio-service
  labels:
    app: kubernetes-2-desafio-service
spec:
  selector:
    app: kubernetes-2-desafio-pod
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 31007
    
